export const SERVER_GENERATION = 1;
export const MAX_MESSAGE_LENGTH = 10000;
export const MAX_THREAD_TITLE_LENGTH = 120;
export const MAX_CHANNEL_NAME_LENGTH = 80;
export const MAX_CHANNEL_DESCRIPTION_LENGTH = 1024;
